/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as FridgeRouteImport } from './routes/fridge'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodFoodIdRouteImport } from './routes/food.$foodId'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiSetupAdminRouteImport } from './routes/api/setup-admin'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FridgeRoute = FridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodFoodIdRoute = FoodFoodIdRouteImport.update({
  id: '/food/$foodId',
  path: '/food/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupAdminRoute = ApiSetupAdminRouteImport.update({
  id: '/api/setup-admin',
  path: '/api/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/fridge': typeof FridgeRoute
  '/orders': typeof OrdersRoute
  '/saved': typeof SavedRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/fridge': typeof FridgeRoute
  '/orders': typeof OrdersRoute
  '/saved': typeof SavedRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/fridge': typeof FridgeRoute
  '/orders': typeof OrdersRoute
  '/saved': typeof SavedRoute
  '/api/setup-admin': typeof ApiSetupAdminRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/food/$foodId': typeof FoodFoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/fridge'
    | '/orders'
    | '/saved'
    | '/api/setup-admin'
    | '/api/telegram'
    | '/food/$foodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/fridge'
    | '/orders'
    | '/saved'
    | '/api/setup-admin'
    | '/api/telegram'
    | '/food/$foodId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/catalog'
    | '/fridge'
    | '/orders'
    | '/saved'
    | '/api/setup-admin'
    | '/api/telegram'
    | '/food/$foodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  FridgeRoute: typeof FridgeRoute
  OrdersRoute: typeof OrdersRoute
  SavedRoute: typeof SavedRoute
  ApiSetupAdminRoute: typeof ApiSetupAdminRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  FoodFoodIdRoute: typeof FoodFoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fridge': {
      id: '/fridge'
      path: '/fridge'
      fullPath: '/fridge'
      preLoaderRoute: typeof FridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$foodId': {
      id: '/food/$foodId'
      path: '/food/$foodId'
      fullPath: '/food/$foodId'
      preLoaderRoute: typeof FoodFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-admin': {
      id: '/api/setup-admin'
      path: '/api/setup-admin'
      fullPath: '/api/setup-admin'
      preLoaderRoute: typeof ApiSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  FridgeRoute: FridgeRoute,
  OrdersRoute: OrdersRoute,
  SavedRoute: SavedRoute,
  ApiSetupAdminRoute: ApiSetupAdminRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  FoodFoodIdRoute: FoodFoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
